'use strict';

/**
 * ============================================================
 *  server.js  —  Fabric Gateway Express Backend
 * ============================================================
 *
 *  ARCHITECTURE OVERVIEW
 *  ─────────────────────
 *  Browser  ──HTTP/REST──▶  Express (this file)  ──gRPC──▶  Fabric Peer
 *
 *  WHY A BACKEND SERVER?
 *  The @hyperledger/fabric-gateway SDK runs in Node.js only.
 *  It cannot run directly in a browser because it needs:
 *    1. Access to the filesystem (TLS certs, user identity files)
 *    2. The gRPC protocol, which browsers don't support natively
 *  So this server acts as a "bridge" between your browser UI
 *  and the Fabric network.
 *
 *  KEY FABRIC CONCEPTS DEMONSTRATED HERE
 *  ──────────────────────────────────────
 *  • gRPC Connection  : Low-level TLS-encrypted channel to the peer
 *  • Identity         : Who you are (certificate + private key from MSP)
 *  • Gateway          : The main entry point to Fabric operations
 *  • Network          : Represents a channel (e.g. "mychannel")
 *  • Contract         : A deployed chaincode (e.g. "basic")
 *  • evaluate()       : READ  — queries the ledger, NOT committed to chain
 *  • submit()         : WRITE — endorsed, ordered, committed to chain
 *  • Chaincode Events : Async notifications from chaincode after commit
 * ============================================================
 */

const express    = require('express');
const cors       = require('cors');
const path       = require('path');
const fs         = require('fs');
const crypto     = require('crypto');
const grpc       = require('@grpc/grpc-js');
const { connect, hash, signers } = require('@hyperledger/fabric-gateway');

// ── App ────────────────────────────────────────────────────────────────────────
const app  = express();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, '../public')));

// ── Fabric Network Configuration ──────────────────────────────────────────────
//
//  These paths point to the crypto material generated by the test-network.
//  After running `./network.sh up createChannel -ca`, your fabric-samples
//  directory will have these files.
//
//  IMPORTANT: Update FABRIC_SAMPLES_PATH to match your actual path!
//
// Auto-detect fabric-samples location.
// Checks common locations in order; the first one that exists wins.
// You can always override by setting the FABRIC_SAMPLES_PATH env variable.
function detectFabricSamplesPath() {
    if (process.env.FABRIC_SAMPLES_PATH) return process.env.FABRIC_SAMPLES_PATH;

    const candidates = [
        // GitHub Codespaces — fabric-samples cloned inside the workspace repo
        path.join('/workspaces', ...(process.env.CODESPACE_NAME
            ? [process.env.CODESPACE_NAME]
            : (process.env.PWD || '').split(path.sep).filter(Boolean).slice(0, 3)
        ), 'fabric-samples'),
        // Any /workspaces/* subfolder (scan one level deep)
        ...( fs.existsSync('/workspaces')
            ? fs.readdirSync('/workspaces')
                .map(d => path.join('/workspaces', d, 'fabric-samples'))
            : []
        ),
        // Standard home-directory clone
        path.join(process.env.HOME, 'fabric-samples'),
        // Current working directory
        path.join(process.cwd(), 'fabric-samples'),
        // One level up from cwd
        path.join(process.cwd(), '..', 'fabric-samples'),
    ];

    for (const candidate of candidates) {
        try {
            // A valid fabric-samples has a test-network folder inside
            if (fs.statSync(path.join(candidate, 'test-network')).isDirectory()) {
                return candidate;
            }
        } catch { /* not found, try next */ }
    }

    // Fall back to home — checkPrerequisites() will report the missing files
    return path.join(process.env.HOME, 'fabric-samples');
}

const FABRIC_SAMPLES_PATH = detectFabricSamplesPath();
console.log(`[config] fabric-samples path: ${FABRIC_SAMPLES_PATH}`);

const config = {
    // The channel name used when you ran `./network.sh up createChannel`
    channelName:   process.env.CHANNEL_NAME   || 'mychannel',

    // The chaincode name used when you ran `./network.sh deployCC -ccn basic ...`
    chaincodeName: process.env.CHAINCODE_NAME || 'basic',

    // Which organisation's peer we connect to
    mspId:         process.env.MSP_ID         || 'Org1MSP',

    // The peer's gRPC endpoint (host:port)
    // test-network peer0.org1 listens on port 7051
    peerEndpoint:  process.env.PEER_ENDPOINT  || 'localhost:7051',

    // The hostname in the peer's TLS certificate
    peerHostAlias: process.env.PEER_HOST_ALIAS || 'peer0.org1.example.com',

    // Path to the peer's TLS CA certificate (used to verify the peer's identity)
    tlsCertPath: path.join(
        FABRIC_SAMPLES_PATH,
        'test-network/organizations/peerOrganizations/org1.example.com',
        'peers/peer0.org1.example.com/tls/ca.crt'
    ),

    // Path to the user's certificate (proves WHO you are to the network)
    certDirectoryPath: path.join(
        FABRIC_SAMPLES_PATH,
        'test-network/organizations/peerOrganizations/org1.example.com',
        'users/User1@org1.example.com/msp/signcerts'
    ),

    // Path to the user's private key (used to SIGN transactions)
    keyDirectoryPath: path.join(
        FABRIC_SAMPLES_PATH,
        'test-network/organizations/peerOrganizations/org1.example.com',
        'users/User1@org1.example.com/msp/keystore'
    ),
};

// ── Fabric Connection (singleton — reused across requests) ────────────────────
//
//  We create ONE gRPC connection and ONE Gateway per server process.
//  Creating these is expensive; reusing them is efficient.
//
//  LAZY INITIALISATION: We do NOT connect at server startup. We wait until
//  the first API call arrives. This means the web server starts fine even if
//  the Fabric network is not yet running — the UI can show a helpful "not
//  connected" state rather than a raw crash.
//
let gatewayClient = null;   // the @hyperledger/fabric-gateway Gateway object
let grpcClient    = null;   // the underlying gRPC channel

/**
 * Reads the first file in a directory.
 * Fabric stores certs and keys with auto-generated filenames, so we just
 * grab whichever file is there rather than hard-coding the exact filename.
 */
function readFirstFileInDir(dirPath) {
    const files = fs.readdirSync(dirPath);
    if (files.length === 0) throw new Error(`No files found in ${dirPath}`);
    return fs.readFileSync(path.join(dirPath, files[0]));
}

/**
 * Checks whether the crypto files generated by the test-network exist.
 * Returns a structured diagnostic object so the UI can show exactly
 * which step is missing (network not started vs chaincode not deployed, etc.)
 *
 * The test-network generates these files when you run:
 *   ./network.sh up createChannel -ca
 */
function checkPrerequisites() {
    const checks = [
        {
            label: 'Peer TLS certificate',
            path:  config.tlsCertPath,
            hint:  'Run: ./network.sh up createChannel -ca',
            exists: false,
        },
        {
            label: 'User signing certificate',
            path:  config.certDirectoryPath,
            hint:  'Run: ./network.sh up createChannel -ca',
            exists: false,
            isDir: true,
        },
        {
            label: 'User private key',
            path:  config.keyDirectoryPath,
            hint:  'Run: ./network.sh up createChannel -ca',
            exists: false,
            isDir: true,
        },
    ];

    let allPresent = true;
    for (const check of checks) {
        try {
            const stat = fs.statSync(check.path);
            // For directories, also verify they contain at least one file
            if (check.isDir) {
                const files = fs.readdirSync(check.path);
                check.exists = files.length > 0;
            } else {
                check.exists = stat.isFile();
            }
        } catch {
            check.exists = false;
        }
        if (!check.exists) allPresent = false;
    }

    return { allPresent, checks, fabricSamplesPath: FABRIC_SAMPLES_PATH };
}

/**
 * Creates a gRPC channel to the Fabric peer, secured with TLS.
 *
 * gRPC is the transport protocol that Fabric uses internally.
 * Think of it like HTTP but binary, faster, and streaming-capable.
 * The TLS certificate ensures we're talking to the right peer.
 */
async function newGrpcConnection() {
    const tlsRootCert    = fs.readFileSync(config.tlsCertPath);
    const tlsCredentials = grpc.credentials.createSsl(tlsRootCert);

    return new grpc.Client(
        config.peerEndpoint,
        tlsCredentials,
        {
            // This tells gRPC which hostname to expect in the peer's TLS cert.
            // Needed when connecting via localhost but the cert says peer0.org1.example.com
            'grpc.ssl_target_name_override': config.peerHostAlias,
        }
    );
}

/**
 * Creates a Fabric Gateway connection.
 *
 * The Gateway is your main API handle. It wraps the gRPC connection
 * and adds Fabric-specific logic: transaction proposals, endorsement,
 * ordering, commit waiting, and event listening.
 *
 * Identity  = "who are you?"  → your X.509 certificate
 * Signer    = "prove it"      → your private key used to sign proposals
 * Hash      = "which hash fn" → SHA-256 (standard for Fabric)
 */
async function newGateway(client) {
    const certificate   = readFirstFileInDir(config.certDirectoryPath);
    const privateKeyPem = readFirstFileInDir(config.keyDirectoryPath);
    const privateKey    = crypto.createPrivateKey(privateKeyPem);

    return connect({
        client,                                     // the gRPC channel
        identity: { mspId: config.mspId, credentials: certificate },
        signer: signers.newPrivateKeySigner(privateKey),
        hash: hash.sha256,
    });
}

/**
 * Returns (or lazily creates) the singleton Gateway.
 * All API routes call this to get a contract reference.
 *
 * If the crypto files don't exist yet (network not started), this throws
 * with a clear message. The caller catches it and returns a 503 with
 * actionable instructions.
 *
 * If a previous connection attempt failed, we reset the singleton so the
 * next request tries again — this lets you start the network AFTER the
 * web server is already running, and the app reconnects automatically.
 */
async function getContract() {
    if (!gatewayClient) {
        // Check prerequisites first — gives a much clearer error than
        // letting the fs.readFileSync throw a raw ENOENT.
        const pre = checkPrerequisites();
        if (!pre.allPresent) {
            const missing = pre.checks
                .filter(c => !c.exists)
                .map(c => `  ✗ ${c.label}`)
                .join('\n');
            throw new Error(
                `Fabric test-network crypto material not found.\n\n` +
                `Missing files:\n${missing}\n\n` +
                `Fix: cd ~/fabric-samples/test-network && ` +
                `./network.sh up createChannel -ca`
            );
        }

        try {
            grpcClient    = await newGrpcConnection();
            gatewayClient = await newGateway(grpcClient);
        } catch (err) {
            // Reset so the next request retries instead of reusing a broken state
            grpcClient    = null;
            gatewayClient = null;
            throw err;
        }
    }

    // network  = a channel (ledger + smart contracts)
    // contract = a specific chaincode on that channel
    const network  = gatewayClient.getNetwork(config.channelName);
    const contract = network.getContract(config.chaincodeName);
    return { contract, network };
}

// ══════════════════════════════════════════════════════════════════════════════
//  REST API ROUTES
//  Each route maps to a chaincode function in asset-transfer-basic
// ══════════════════════════════════════════════════════════════════════════════

// ── Health / Status ───────────────────────────────────────────────────────────
//
//  Returns the connection status AND a preflight check so the UI can
//  distinguish between "network not started" and "peer unreachable".
//
app.get('/api/status', async (req, res) => {
    const preflight = checkPrerequisites();

    // If crypto files are missing, we know exactly why we can't connect --
    // report it clearly without attempting a gRPC connection that would crash.
    if (!preflight.allPresent) {
        return res.status(503).json({
            status: 'no_crypto',
            error:  'Fabric test-network crypto files are missing. Has the network been started?',
            preflight,
            config: {
                channel:   config.channelName,
                chaincode: config.chaincodeName,
                mspId:     config.mspId,
                peer:      config.peerEndpoint,
            },
        });
    }

    try {
        // Crypto files exist — attempt the actual gRPC connection
        await getContract();
        res.json({
            status: 'connected',
            preflight,
            config: {
                channel:   config.channelName,
                chaincode: config.chaincodeName,
                mspId:     config.mspId,
                peer:      config.peerEndpoint,
            },
        });
    } catch (err) {
        // Files exist but peer is unreachable (e.g. Docker containers stopped)
        res.status(503).json({
            status: 'peer_unreachable',
            error:  err.message,
            preflight,
            config: {
                channel:   config.channelName,
                chaincode: config.chaincodeName,
                mspId:     config.mspId,
                peer:      config.peerEndpoint,
            },
        });
    }
});


// ── GET /api/preflight  →  Prerequisite file check ───────────────────────────
//
//  Returns a structured checklist of whether the crypto files exist.
//  The frontend uses this to show a step-by-step setup guide when the
//  network has not been started yet, instead of a raw error message.
//
app.get("/api/preflight", (req, res) => {
    const result = checkPrerequisites();
    res.json(result);
});

// ── GET /api/assets  →  GetAllAssets ─────────────────────────────────────────
//
//  contract.evaluateTransaction() = READ ONLY
//
//  "Evaluate" means:
//    1. Send the request to the peer
//    2. Peer simulates the chaincode and returns the result
//    3. Result is returned to us — NOT written to the ledger
//    4. No ordering, no consensus — just a local ledger query
//
//  Use evaluate for anything that reads data (no side effects).
//
app.get('/api/assets', async (req, res) => {
    try {
        const { contract } = await getContract();

        // evaluateTransaction sends to peer and returns chaincode response bytes
        const resultBytes = await contract.evaluateTransaction('GetAllAssets');

        // The chaincode returns JSON bytes; we decode and parse them
        const result = JSON.parse(Buffer.from(resultBytes).toString());
        res.json({ success: true, data: result });
    } catch (err) {
        res.status(500).json({ success: false, error: err.message });
    }
});

// ── GET /api/assets/:id  →  ReadAsset ────────────────────────────────────────
app.get('/api/assets/:id', async (req, res) => {
    try {
        const { contract } = await getContract();

        // Pass arguments after the function name — they map to chaincode params
        const resultBytes = await contract.evaluateTransaction('ReadAsset', req.params.id);
        const result = JSON.parse(Buffer.from(resultBytes).toString());
        res.json({ success: true, data: result });
    } catch (err) {
        res.status(404).json({ success: false, error: err.message });
    }
});

// ── POST /api/assets  →  CreateAsset ─────────────────────────────────────────
//
//  contract.submitTransaction() = WRITE (state-changing)
//
//  "Submit" means:
//    1. Client sends a transaction PROPOSAL to the endorsing peer(s)
//    2. Peer simulates it and returns an ENDORSEMENT (signed result)
//    3. Client sends the endorsed proposal to the ORDERER
//    4. Orderer batches it into a block and sends to all peers
//    5. Peers COMMIT the block to their copy of the ledger
//    6. submitTransaction() returns only after step 5 — the ledger is updated
//
//  This is the full Fabric transaction lifecycle!
//
app.post('/api/assets', async (req, res) => {
    try {
        const { contract } = await getContract();
        const { id, color, size, owner, appraisedValue } = req.body;

        if (!id || !color || !size || !owner || !appraisedValue) {
            return res.status(400).json({
                success: false,
                error: 'Missing required fields: id, color, size, owner, appraisedValue'
            });
        }

        // All arguments must be strings for chaincode
        await contract.submitTransaction(
            'CreateAsset',
            id,
            color,
            String(size),
            owner,
            String(appraisedValue)
        );

        res.json({ success: true, message: `Asset ${id} created and committed to ledger` });
    } catch (err) {
        res.status(500).json({ success: false, error: err.message });
    }
});

// ── PUT /api/assets/:id/transfer  →  TransferAsset ───────────────────────────
app.put('/api/assets/:id/transfer', async (req, res) => {
    try {
        const { contract } = await getContract();
        const { newOwner } = req.body;

        if (!newOwner) {
            return res.status(400).json({ success: false, error: 'Missing required field: newOwner' });
        }

        const resultBytes = await contract.submitTransaction(
            'TransferAsset',
            req.params.id,
            newOwner
        );

        // TransferAsset returns the previous owner name
        const previousOwner = Buffer.from(resultBytes).toString() || 'unknown';
        res.json({
            success: true,
            message: `Asset ${req.params.id} transferred from ${previousOwner} to ${newOwner}`
        });
    } catch (err) {
        res.status(500).json({ success: false, error: err.message });
    }
});

// ── PUT /api/assets/:id  →  UpdateAsset ──────────────────────────────────────
app.put('/api/assets/:id', async (req, res) => {
    try {
        const { contract } = await getContract();
        const { color, size, owner, appraisedValue } = req.body;

        if (!color || !size || !owner || !appraisedValue) {
            return res.status(400).json({
                success: false,
                error: 'Missing required fields: color, size, owner, appraisedValue'
            });
        }

        await contract.submitTransaction(
            'UpdateAsset',
            req.params.id,
            color,
            String(size),
            owner,
            String(appraisedValue)
        );

        res.json({ success: true, message: `Asset ${req.params.id} updated and committed to ledger` });
    } catch (err) {
        res.status(500).json({ success: false, error: err.message });
    }
});

// ── DELETE /api/assets/:id  →  DeleteAsset ───────────────────────────────────
app.delete('/api/assets/:id', async (req, res) => {
    try {
        const { contract } = await getContract();

        await contract.submitTransaction('DeleteAsset', req.params.id);
        res.json({ success: true, message: `Asset ${req.params.id} deleted from ledger` });
    } catch (err) {
        res.status(500).json({ success: false, error: err.message });
    }
});

// ── POST /api/ledger/init  →  InitLedger ─────────────────────────────────────
app.post('/api/ledger/init', async (req, res) => {
    try {
        const { contract } = await getContract();
        await contract.submitTransaction('InitLedger');
        res.json({ success: true, message: 'Ledger initialised with sample assets' });
    } catch (err) {
        res.status(500).json({ success: false, error: err.message });
    }
});

// ── GET /api/assets/:id/exists  →  AssetExists ───────────────────────────────
app.get('/api/assets/:id/exists', async (req, res) => {
    try {
        const { contract } = await getContract();
        const resultBytes = await contract.evaluateTransaction('AssetExists', req.params.id);
        const exists = Buffer.from(resultBytes).toString() === 'true';
        res.json({ success: true, exists });
    } catch (err) {
        res.status(500).json({ success: false, error: err.message });
    }
});

// ── GET /api/events/chaincode  →  Chaincode Event Listener ───────────────────
//
//  This route uses Server-Sent Events (SSE) to stream chaincode events
//  to the browser in real time.
//
//  WHAT ARE CHAINCODE EVENTS?
//  When a chaincode function runs, it can emit a named event (e.g. "Transfer").
//  After the transaction is committed to the ledger, the Fabric Gateway
//  delivers those events to subscribers.
//
//  network.getChaincodeEvents() returns an async iterable of event objects.
//  Each event has: chaincodeId, eventName, transactionId, payload.
//
//  SSE (Server-Sent Events) lets the server push messages to the browser
//  over a long-lived HTTP connection — perfect for streaming live events.
//
app.get('/api/events/chaincode', async (req, res) => {
    // SSE headers — tell browser to keep the connection open
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.flushHeaders();

    let eventStream = null;

    const send = (data) => {
        // SSE format: "data: <json>\n\n"
        res.write(`data: ${JSON.stringify(data)}\n\n`);
    };

    try {
        const { network } = await getContract();

        // getChaincodeEvents() subscribes to ALL events emitted by this chaincode
        // startBlock: 0n means "replay from the beginning of the ledger"
        eventStream = await network.getChaincodeEvents(config.chaincodeName, {
            startBlock: BigInt(0),
        });

        send({ type: 'connected', message: 'Listening for chaincode events...' });

        // Iterate over the async stream — each iteration yields one event
        for await (const event of eventStream) {
            const payload = event.payload
                ? JSON.parse(Buffer.from(event.payload).toString())
                : null;

            send({
                type:          'chaincode_event',
                eventName:     event.eventName,
                transactionId: event.transactionId,
                payload,
                timestamp:     new Date().toISOString(),
            });
        }
    } catch (err) {
        if (!res.writableEnded) {
            send({ type: 'error', message: err.message });
        }
    } finally {
        // Always close the event stream when the client disconnects
        if (eventStream) {
            eventStream.close();
        }
    }

    // Clean up when the browser closes the SSE connection
    req.on('close', () => {
        if (eventStream) eventStream.close();
    });
});

// ── GET /api/config ──────────────────────────────────────────────────────────
app.get('/api/config', (req, res) => {
    res.json({
        channelName:   config.channelName,
        chaincodeName: config.chaincodeName,
        mspId:         config.mspId,
        peerEndpoint:  config.peerEndpoint,
        fabricSamplesPath: FABRIC_SAMPLES_PATH,
    });
});

// ── Graceful shutdown ────────────────────────────────────────────────────────
process.on('SIGINT', () => {
    console.log('\nShutting down gracefully...');
    if (gatewayClient) gatewayClient.close();
    if (grpcClient)    grpcClient.close();
    process.exit(0);
});

// ── Start ─────────────────────────────────────────────────────────────────────
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`
╔═══════════════════════════════════════════════════════╗
║       Fabric Gateway Web App — Server Started         ║
╠═══════════════════════════════════════════════════════╣
║  URL       : http://localhost:${PORT}                    ║
║  Channel   : ${config.channelName}                                ║
║  Chaincode : ${config.chaincodeName}                                    ║
║  MSP       : ${config.mspId}                                  ║
║  Peer      : ${config.peerEndpoint}                           ║
╚═══════════════════════════════════════════════════════╝

Make sure your test-network is running:
  cd ~/fabric-samples/test-network
  ./network.sh up createChannel -ca
  ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-go/ -ccl go
`);
});